import Database from 'better-sqlite3';
import { WindowManager } from '../window-manager';
import { registerTabsIpc } from './tabs';
import { registerNavigationIpc } from './navigation';
import { registerProfilesIpc } from './profiles';
import { registerSettingsIpc } from './settings';
import { registerPermissionsIpc } from './permissions';
import { registerHistoryIpc } from './history';
import { registerBookmarksIpc } from './bookmarks';
import { registerDownloadsIpc } from './downloads';
import { registerAIIpc } from './ai';
import { registerAdblockIpc } from './adblock';
import { registerReaderIpc } from './reader';
import { registerInjectionsIpc } from './injections';
import { registerFindIpc } from './find';
import { registerKeywordsIpc } from './keywords';
import { registerOnboardingIpc } from './onboarding';
import { registerAppManagementIpc } from './app-management';
import { registerWindowControlsIpc } from './window-controls';
import { registerAuthIpc } from './auth';
import { KeywordService } from '../services/keyword-service';
import { CrashRecoveryService } from '../services/crash-recovery';

export function registerAllIpc(db: Database.Database, wm: WindowManager): void {
  const keywordService = new KeywordService(db);
  const crashRecovery = new CrashRecoveryService();
  registerTabsIpc(db, wm, crashRecovery);
  registerNavigationIpc(wm);
  registerProfilesIpc(db, wm);
  registerSettingsIpc(db);
  registerPermissionsIpc(wm);
  registerHistoryIpc(db);
  registerBookmarksIpc(db);
  registerDownloadsIpc(db, wm);
  registerAIIpc(db, wm);
  registerAdblockIpc(db);
  registerReaderIpc();
  registerInjectionsIpc(db);
  registerFindIpc();
  registerKeywordsIpc(keywordService);
  registerOnboardingIpc(wm);
  registerAppManagementIpc();
  registerWindowControlsIpc(wm);
  registerAuthIpc(wm);
}
