const DEFAULT_SHORTCUTS = [
  // ── Tabs & Windows ──────────────────────────────────────────────────────────
  {
    id: 'new-tab',
    category: 'Tabs & Windows',
    label: 'New Tab',
    description: 'Opens a new tab',
    mac: { key: 't', meta: true },
    win: { key: 't', ctrl: true },
  },
  {
    id: 'new-window',
    category: 'Tabs & Windows',
    label: 'New Window',
    description: 'Opens a new browser window',
    mac: { key: 'n', meta: true },
    win: { key: 'n', ctrl: true },
  },
  {
    id: 'close-tab',
    category: 'Tabs & Windows',
    label: 'Close Tab',
    description: 'Closes the current tab',
    mac: { key: 'w', meta: true },
    win: { key: 'w', ctrl: true },
  },
  {
    id: 'restore-tab',
    category: 'Tabs & Windows',
    label: 'Restore Tab',
    description: 'Reopens the last closed tab',
    mac: { key: 't', meta: true, shift: true },
    win: { key: 't', ctrl: true, shift: true },
  },
  {
    id: 'next-tab',
    category: 'Tabs & Windows',
    label: 'Next Tab',
    description: 'Switch to the next tab',
    mac: { key: 'arrowright', meta: true, alt: true },
    win: { key: 'tab', ctrl: true },
  },
  {
    id: 'prev-tab',
    category: 'Tabs & Windows',
    label: 'Previous Tab',
    description: 'Switch to the previous tab',
    mac: { key: 'arrowleft', meta: true, alt: true },
    win: { key: 'tab', ctrl: true, shift: true },
  },
  {
    id: 'tab-1',
    category: 'Tabs & Windows',
    label: 'Switch to Tab 1',
    description: 'Jump to the first tab',
    mac: { key: '1', meta: true },
    win: { key: '1', ctrl: true },
  },
  {
    id: 'tab-2',
    category: 'Tabs & Windows',
    label: 'Switch to Tab 2',
    description: 'Jump to the second tab',
    mac: { key: '2', meta: true },
    win: { key: '2', ctrl: true },
  },
  {
    id: 'tab-3',
    category: 'Tabs & Windows',
    label: 'Switch to Tab 3',
    description: 'Jump to the third tab',
    mac: { key: '3', meta: true },
    win: { key: '3', ctrl: true },
  },
  {
    id: 'tab-4',
    category: 'Tabs & Windows',
    label: 'Switch to Tab 4',
    description: 'Jump to the fourth tab',
    mac: { key: '4', meta: true },
    win: { key: '4', ctrl: true },
  },
  {
    id: 'tab-5',
    category: 'Tabs & Windows',
    label: 'Switch to Tab 5',
    description: 'Jump to the fifth tab',
    mac: { key: '5', meta: true },
    win: { key: '5', ctrl: true },
  },
  {
    id: 'tab-6',
    category: 'Tabs & Windows',
    label: 'Switch to Tab 6',
    description: 'Jump to the sixth tab',
    mac: { key: '6', meta: true },
    win: { key: '6', ctrl: true },
  },
  {
    id: 'tab-7',
    category: 'Tabs & Windows',
    label: 'Switch to Tab 7',
    description: 'Jump to the seventh tab',
    mac: { key: '7', meta: true },
    win: { key: '7', ctrl: true },
  },
  {
    id: 'tab-8',
    category: 'Tabs & Windows',
    label: 'Switch to Tab 8',
    description: 'Jump to the eighth tab',
    mac: { key: '8', meta: true },
    win: { key: '8', ctrl: true },
  },
  {
    id: 'last-tab',
    category: 'Tabs & Windows',
    label: 'Switch to Last Tab',
    description: 'Jump to the last tab',
    mac: { key: '9', meta: true },
    win: { key: '9', ctrl: true },
  },
  {
    id: 'fullscreen',
    category: 'Tabs & Windows',
    label: 'Toggle Fullscreen',
    description: 'Enter or exit fullscreen mode',
    mac: { key: 'f', meta: true, ctrl: true },
    win: { key: 'F11' },
  },
  {
    id: 'minimize',
    category: 'Tabs & Windows',
    label: 'Minimize Window',
    description: 'Minimize the browser window',
    mac: { key: 'm', meta: true },
    win: { key: 'm', meta: true },
  },
  {
    id: 'quit',
    category: 'Tabs & Windows',
    label: 'Quit',
    description: 'Quit the browser',
    mac: { key: 'q', meta: true },
    win: { key: 'F4', alt: true },
  },

  // ── Navigation ──────────────────────────────────────────────────────────────
  {
    id: 'back',
    category: 'Navigation',
    label: 'Go Back',
    description: 'Navigate back in history',
    mac: { key: '[', meta: true },
    win: { key: 'arrowleft', alt: true },
  },
  {
    id: 'forward',
    category: 'Navigation',
    label: 'Go Forward',
    description: 'Navigate forward in history',
    mac: { key: ']', meta: true },
    win: { key: 'arrowright', alt: true },
  },
  {
    id: 'reload',
    category: 'Navigation',
    label: 'Reload',
    description: 'Reload the current page',
    mac: { key: 'r', meta: true },
    win: { key: 'r', ctrl: true },
  },
  {
    id: 'hard-reload',
    category: 'Navigation',
    label: 'Hard Reload',
    description: 'Reload page ignoring cache',
    mac: { key: 'r', meta: true, shift: true },
    win: { key: 'r', ctrl: true, shift: true },
  },
  {
    id: 'stop',
    category: 'Navigation',
    label: 'Stop Loading',
    description: 'Stop loading the current page',
    mac: { key: 'escape' },
    win: { key: 'escape' },
  },
  {
    id: 'home',
    category: 'Navigation',
    label: 'Go Home',
    description: 'Navigate to the home page',
    mac: { key: 'home', alt: true },
    win: { key: 'home', alt: true },
  },

  // ── Address Bar ─────────────────────────────────────────────────────────────
  {
    id: 'focus-address',
    category: 'Address Bar',
    label: 'Focus Address Bar',
    description: 'Focus and select the address bar',
    mac: { key: 'l', meta: true },
    win: { key: 'l', ctrl: true },
    allowInInput: true,
  },
  {
    id: 'focus-search',
    category: 'Address Bar',
    label: 'Focus Search',
    description: 'Focus the address bar for searching',
    mac: { key: 'k', meta: true },
    win: { key: 'k', ctrl: true },
    allowInInput: true,
  },

  // ── Page Controls ───────────────────────────────────────────────────────────
  {
    id: 'zoom-in',
    category: 'Page Controls',
    label: 'Zoom In',
    description: 'Increase page zoom level',
    mac: { key: '=', meta: true },
    win: { key: '=', ctrl: true },
  },
  {
    id: 'zoom-out',
    category: 'Page Controls',
    label: 'Zoom Out',
    description: 'Decrease page zoom level',
    mac: { key: '-', meta: true },
    win: { key: '-', ctrl: true },
  },
  {
    id: 'zoom-reset',
    category: 'Page Controls',
    label: 'Reset Zoom',
    description: 'Reset page zoom to 100%',
    mac: { key: '0', meta: true },
    win: { key: '0', ctrl: true },
  },
  {
    id: 'find',
    category: 'Page Controls',
    label: 'Find in Page',
    description: 'Open find bar to search in page',
    mac: { key: 'f', meta: true },
    win: { key: 'f', ctrl: true },
  },
  {
    id: 'print',
    category: 'Page Controls',
    label: 'Print',
    description: 'Print the current page',
    mac: { key: 'p', meta: true },
    win: { key: 'p', ctrl: true },
  },

  // ── Developer Tools ─────────────────────────────────────────────────────────
  {
    id: 'devtools',
    category: 'Developer Tools',
    label: 'Open DevTools',
    description: 'Open browser developer tools',
    mac: { key: 'i', meta: true, alt: true },
    win: { key: 'i', ctrl: true, shift: true },
  },
  {
    id: 'devtools-console',
    category: 'Developer Tools',
    label: 'DevTools Console',
    description: 'Open developer tools console',
    mac: { key: 'j', meta: true, alt: true },
    win: { key: 'j', ctrl: true, shift: true },
  },
  {
    id: 'view-source',
    category: 'Developer Tools',
    label: 'View Source',
    description: 'View the page source code',
    mac: { key: 'u', meta: true },
    win: { key: 'u', ctrl: true },
  },

  // ── Browser Features ────────────────────────────────────────────────────────
  {
    id: 'history',
    category: 'Browser Features',
    label: 'History',
    description: 'Open browser history',
    mac: { key: 'h', meta: true },
    win: { key: 'h', ctrl: true },
  },
  {
    id: 'downloads',
    category: 'Browser Features',
    label: 'Downloads',
    description: 'Open downloads page',
    mac: { key: 'j', meta: true },
    win: { key: 'j', ctrl: true },
  },
  {
    id: 'bookmarks',
    category: 'Browser Features',
    label: 'Bookmarks',
    description: 'Open bookmarks manager',
    mac: { key: 'o', meta: true, shift: true },
    win: { key: 'o', ctrl: true, shift: true },
  },
  {
    id: 'bookmark-tab',
    category: 'Browser Features',
    label: 'Bookmark Tab',
    description: 'Bookmark the current tab',
    mac: { key: 'd', meta: true },
    win: { key: 'd', ctrl: true },
  },
  {
    id: 'settings',
    category: 'Browser Features',
    label: 'Settings',
    description: 'Open browser settings',
    mac: { key: ',', meta: true },
    win: { key: ',', ctrl: true },
  },

  // ── Advanced ─────────────────────────────────────────────────────────────────
  {
    id: 'command-palette',
    category: 'Advanced',
    label: 'Command Palette',
    description: 'Open the command palette',
    mac: { key: 'p', meta: true, shift: true },
    win: { key: 'p', ctrl: true, shift: true },
  },
  {
    id: 'shortcuts-help',
    category: 'Advanced',
    label: 'Keyboard Shortcuts',
    description: 'Show keyboard shortcuts cheat sheet',
    mac: { key: 'F1' },
    win: { key: 'F1' },
  },
];

window.DEFAULT_SHORTCUTS = DEFAULT_SHORTCUTS;
